[project]
name = "be-puri"  # Nama proyek Anda

[service "web"]
# Konfigurasi build Docker
build = {
  dockerfile = "./Dockerfile"  # Path relatif ke Dockerfile
}

[service "web"]
# Konfigurasi port yang digunakan aplikasi
port = 4040
