name: Deploy Go Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_NAME=db_puri" >> .env
          echo "PORT=8080" >> .env

      - name: Login to Docker Hub
        run: docker login -u surya161 -p surya9029.

      - name: Build Docker image
        run: docker build -t surya161/puriagung .

      - name: Push image to Docker Hub
        run: docker push surya161/puriagung:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull surya161/puriagung:latest

      - name: Delete old container if exists
        run: docker rm -f puriagung-container || true

      - name: Run Docker container
        run: |
          docker run -d \
            -p 4040:4040 \
            --name puriagung-container \
            --env-file .env \
            surya161/puriagung:latest
