name: Deploy to Railway

on:
  push:
    branches:
      - testdeploy  # Atau branch lain yang ingin Anda deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Railway CLI
      run: curl -sSL https://cli.railway.app/install.sh | sh

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      run: railway up

    # (Opsional) Langkah untuk menjalankan migrasi database
    - name: Run database migrations
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      run: |
        railway run -- [migration command]
